sandbox-quantum/Tangelo

tangelo/linq/qpu_connection/qemist_cloud_connection.py, tangelo/linq/simulator.py
=> Fix QEMIST Cloud function names

dev_tools/pycodestyle, examples/linq/2.qpu_connection.ipynb, tangelo/linq/qpu_connection/__init__.py, tangelo/linq/qpu_connection/ionq_connection.py, tangelo/linq/qpu_connection/qpu_connection.py, tangelo/linq/tests/test_ionq_connection.py
IonQ API python wrapper class and tests, to facilitate the submission of experiments through their portal.
Comes with a notebook.
=> Ionq connection

.github/workflows/create_release_branch.yml, README.rst, setup.py, tangelo/_version.py
Little fix to release workflow, version number and readme.
=> Release prep

tangelo/toolboxes/measurements/estimate_measurements.py
Was it the point of [QSDC-4424](https://1qbit-intra.atlassian.net/browse/QSDC-4424)? That is to say changing the formula to `measurement_per_observable=(coeff_observable/desired_accuracy)^2`.
=> Simplifying formula for n_measurement estimation

tangelo/algorithms/variational/sa_vqe_solver.py, tangelo/algorithms/variational/tests/test_sa_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/linq/circuit.py, tangelo/linq/gate.py, tangelo/linq/tests/test_circuits.py, tangelo/linq/tests/test_gates.py
A bunch of small fixes.
1. copy function in circuit
2. get_resources update for VQESolver and SA_VQESolver
3. Missing comma in list of invertible gates meant swap gate could not be inverted.
=> copy + get_resources + invertible swap gate fix

Dockerfile, README.rst, examples/linq/1.the_basics.ipynb
- Updated docker images with Tangelo install, added small section to README
- Removed QDK from it (pyscf install fails on fedora36, and apparently NET 3.1 is not available anymore for Fedora30. Ubuntu + 3.1 still works in our automated pipeline however).
- Cleaned up linq notebook a bit, as it had been written 2 years+ ago for internal purposes originally.
=> Docker fix

.github/workflows/continuous_integration.yml, setup.py, tangelo/toolboxes/circuits/lcu.py, tangelo/toolboxes/circuits/qsp.py, tangelo/toolboxes/circuits/tests/test_lcu.py, tangelo/toolboxes/circuits/tests/test_qsp.py
The Quantum Signal Processing algorithm for Hamiltonian Simulation as defined by arXiv:2002.11649.
- Uses pyqsp for the phases by default.
- More stable/faster function that uses interface oct2py with octave based QSPPACK also available
=> Quantum Signal Processing time-evolution

tangelo/toolboxes/ansatz_generator/ansatz_utils.py, tangelo/toolboxes/ansatz_generator/tests/test_ansatz_util.py
Adds functionality for even trotter order greater than 2.
=> even Trotter order > 2

tangelo/algorithms/projective/quantum_imaginary_time.py, tangelo/algorithms/variational/sa_vqe_solver.py, tangelo/algorithms/variational/tests/test_adapt_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/linq/circuit.py
Added calls to circuit.depth() in get_resources method of vqe_solver, sa_vqe_solver and quantum_imaginary_time. No other instances were identified
=> Add circuit.depth() in get_resources methods

tangelo/problem_decomposition/incremental/mifno_helper.py
=> Compatibility with new QCloud outputs

examples/excited_states.ipynb, examples/qchem_modelling_basics.ipynb
The link was pointing to google drive. This should have been changed to a local link.
=> Fix link of fig in qchem notebook

tangelo/toolboxes/post_processing/__init__.py, tangelo/toolboxes/post_processing/extrapolation.py, tangelo/toolboxes/post_processing/tests/test_extrapolation.py
- Fixed bug in richardson_analytical (added a sign change depending on number of points, agrees with the numerical extrapolation)
- Added optional error estimation (standard quadratic error propagation)
- Added relevant tests
- Changed order of arguments to keep energies and errors next to each other
=> Enhance extrapolation module

tangelo/algorithms/classical/ccsd_solver.py, tangelo/algorithms/classical/fci_solver.py, tangelo/algorithms/classical/tests/test_ccsd_solver.py, tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/algorithms/variational/tests/test_iqcc_solver.py, tangelo/algorithms/variational/tests/test_tetris_adapt_vqe_solver.py, tangelo/algorithms/variational/tests/test_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/molecule_library.py, tangelo/problem_decomposition/dmet/fragment.py, tangelo/toolboxes/ansatz_generator/_unitary_cc_openshell.py, tangelo/toolboxes/ansatz_generator/adapt_ansatz.py, tangelo/toolboxes/ansatz_generator/hea.py, tangelo/toolboxes/ansatz_generator/ilc.py, tangelo/toolboxes/ansatz_generator/qcc.py, tangelo/toolboxes/ansatz_generator/qmf.py, tangelo/toolboxes/ansatz_generator/tests/test_adapt_ansatz.py, tangelo/toolboxes/ansatz_generator/tests/test_qcc.py, tangelo/toolboxes/ansatz_generator/tests/test_qmf.py, tangelo/toolboxes/ansatz_generator/uccgd.py, tangelo/toolboxes/ansatz_generator/uccsd.py, tangelo/toolboxes/ansatz_generator/upccgsd.py, tangelo/toolboxes/ansatz_generator/vsqs.py, tangelo/toolboxes/molecular_computation/molecule.py, tangelo/toolboxes/molecular_computation/tests/test_molecule.py
Support for UHF reference in SecondQuantizedMolecule.
Works for VQESolver, all ansatz except VSQS and CCSDSolver.
=> UHF reference

tangelo/toolboxes/circuits/discrete_clock.py, tangelo/toolboxes/circuits/grid_circuits.py, tangelo/toolboxes/circuits/multiproduct.py, tangelo/toolboxes/circuits/tests/test_discrete_clock.py, tangelo/toolboxes/circuits/tests/test_grid.py, tangelo/toolboxes/circuits/tests/test_mp.py
Added
1. Circuits to implement kinetic energy and x^2 for first quantized time-evolution
2. Multi-product time-evolution arXiv: 1907.11679
3. Discrete-clock time-evolution for time-dependant systems arXiv: 2203.11353
=> added multi-product, grid_circuits and discrete_clock

.github/workflows/continuous_integration.yml, Dockerfile, tangelo/helpers/utils.py, tangelo/linq/tests/test_translator_circuit.py, tangelo/linq/translator/__init__.py, tangelo/linq/translator/translate_circuit.py, tangelo/linq/translator/translate_pennylane.py
All gates except for MEASURE which does not appear to be supported well in pennylane. A qubit can only be measured once as far as I can tell.
=> translation to pennylane

tangelo/linq/translator/translate_pennylane.py, tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/toolboxes/circuits/tests/test_mp.py
Tests are failing due to a recent merge of "main" into "develop". These revert those changes.
=> reverted changes that broke tests

tangelo/linq/target/backend.py, tangelo/linq/tests/test_simulator.py
Co-authored-by: James Brown <james.brown@1qbit.com>
* fix error for imaginary qubit_op with desired meas result (#278)
=> Bumping develop to 0.3.4

tangelo/linq/gate.py, tangelo/linq/tests/test_gates.py
=> Fix a bug for the S and T gate.inverse() method

tangelo/linq/circuit.py, tangelo/problem_decomposition/incremental/mifno_helper.py
MIFNOHelper print now only returns chemistry-related information.
=> Mifnohelper print: remove problem handle

tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/algorithms/variational/sa_oo_vqe_solver.py, tangelo/algorithms/variational/sa_vqe_solver.py, tangelo/algorithms/variational/tests/test_adapt_vqe_solver.py, tangelo/algorithms/variational/tests/test_sa_vqe_solver.py, tangelo/algorithms/variational/tests/test_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/linq/target/backend.py, tangelo/toolboxes/operators/operators.py, tangelo/toolboxes/operators/tests/test_operators.py
Allows mid-circuit measurement in Ansatz or projective_circuit with desired_meas_result.
=> Arg simulate_options and projective_circuit to VQESolver

tangelo/algorithms/projective/quantum_imaginary_time.py, tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/algorithms/variational/iqcc_ilc_solver.py, tangelo/algorithms/variational/iqcc_solver.py, tangelo/algorithms/variational/sa_oo_vqe_solver.py, tangelo/algorithms/variational/sa_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/oniom/_helpers/helper_classes.py, tangelo/problem_decomposition/oniom/oniom_problem_decomposition.py
Added typing for option dictionaries. Most attributes should now be available to view in a persons coding environment. For example, in VSCode.
=> added typing for option dictionaries

tangelo/algorithms/classical/mp2_solver.py, tangelo/linq/target/backend.py, tangelo/toolboxes/molecular_computation/molecule.py, tangelo/toolboxes/operators/trim_trivial_qubits.py, tangelo/toolboxes/post_processing/post_selection.py, tangelo/toolboxes/qubit_mappings/combinatorial.py
Fixed some typos in the documentation, and code format at some places.
=> Typos in docs

.github/workflows/continuous_integration.yml, dev_tools/pycodestyle, tangelo/algorithms/projective/qpe.py, tangelo/algorithms/projective/tests/test_qpe.py, tangelo/linq/circuit.py, tangelo/linq/helpers/circuits/statevector.py, tangelo/toolboxes/molecular_computation/integral_solver_pyscf.py, tangelo/toolboxes/molecular_computation/tests/test_molecule.py, tangelo/toolboxes/unitary_generator/__init__.py, tangelo/toolboxes/unitary_generator/tests/__init__.py, tangelo/toolboxes/unitary_generator/tests/test_unitaries.py, tangelo/toolboxes/unitary_generator/trotter_suzuki.py, tangelo/toolboxes/unitary_generator/unitary.py, tangelo/toolboxes/unitary_generator/unitary_circuit.py
Here is the basis outline of what a QPESolver could look like.
Contains:
QPESolver
Unitary base class
TrotterSuzuki
=> QPESolver implementation

tangelo/linq/qpu_connection/ibm_connection.py, tangelo/linq/tests/test_ibm_connection.py
Fix following new version of qiskit. Support for multiple circuits for sampler
=> Qiskit runtime update + sampler with list of circuits

tangelo/linq/circuit.py, tangelo/linq/tests/test_circuits.py
- Added `merge_rotations` method and function, that agglomerates compatible rotations acting on the same qubits
- Added `simplify` method and function that applies cycles of (remove small rotation + merge rotations + remove redundant gates) until no change occur anymore or a max cycle.
- `remove_qubit` option added and set to false: by default qubits with no operations on them are not removed from the circuit to avoid code breaking sneakily. Users can use attributes of the circuit object to identify them and remove manually, or use the trim functions to cut them off a circuit and Hamiltonian before computing an expectation value for instance.
I reused our T3 hands-on on VQE to simply grab the optimal VQE UCCSD circuit for H2 321-g (1200 gates, a few var params below 1e-4, therefore …
=> Simplify method for circuits

tangelo/molecule_library.py
Test of hypothesis for failing test.
=> added explicit mo_coeff for H4_cation

tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/linq/circuit.py
First-time contributor here !! Pretty interesting projects 
I have worked on fixing the bug: Circuit. draw() returns an error when the gate parameter is a string
It was a straightforward task and didn't take a lot of time, I have also written the code with spend in mine, For a 100 gate it takes less than a second to draw the output, I have not written a test or doc wanted to get the teams approval after which will finish up with test cases for the draw and _string_to_sympy methods.
The attached collab will give an example of the newer code in motion, I have created a random gate generator that generates n gates( currently set to 100 and n_qubits =2) 
Link: 
Fix for Issue: #388 
Colab: https://colab.research.google.com/drive/1g4ll38cIn-27-tB4KCYNzV6gp6MK-Bzk?usp=sharing
=> Improving draw method

.github/workflows/semgrep.yml
=> Semgrep scanning

.github/workflows/continuous_integration.yml, .github/workflows/create_release_branch.yml
In reaction to "Command Injection vulnerabilities in sandbox-quantum/Tangelo in 3 locations". Verison number is now encapsulated in an environment variable and shell substitution is done in a way that prevents injection
=> security patch semgrep
