sandbox-quantum/Tangelo

tangelo/algorithms/variational/adapt_vqe_solver.py
`spin` was not defined with a `qubit_hamiltonian`, but it is needed to convert the pool of fermion operators to qubit operators.
=> Fix the need for spin with a qubit operator + pool of fermion operators

tangelo/algorithms/classical/fci_solver.py, tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/toolboxes/molecular_computation/molecule.py, tangelo/toolboxes/qubit_mappings/mapping_transform.py
The main events:
- Restriction of the frozen orbitals (can't freeze orbitals with occupation == 1). There are inconsistencies with `pyscf` solvers when freezing half-filled MOs. At the moment, CASCI and MP2 do not work, CCSD does. Therefore, I think it is a good idea to raise an error until the issue https://github.com/pyscf/pyscf/issues/1331 is fixed/resolved.
- Changed qubits to spinorbitals in the fermion to qubit mapping function.
- Removed unused `frozen_orbitals` in `ADAPTSolver`.
- Fixed orbital selection in `FCISolver`.
- `VQESolver` raises an error when there is no var_params in the circuit.
=> Added restrictions for the frozen orbitals + FCISolver active space selection

tangelo/toolboxes/qubit_mappings/statevector_mapping.py, tangelo/toolboxes/qubit_mappings/tests/test_statevector_mapping.py
There are two Bravyi-Kitaev transformations that are different if the number of qubits is not a power of 2. The current implementation used `bravyi_kitaev` for the reference state and `bravyi_kitaev_tree` for the SCBK mapping causing issues in certain instances. The example I came across was 
`mol = SecondQuantizedMolecule(xyz_H2O, 0, 0, "sto-3g", frozen_orbitals=[0, 7])`
which is now tested and passes.
=> Fix scbk reference state

tangelo/linq/gate.py, tangelo/linq/tests/test_gates.py
Naive attempt at fixing https://github.com/goodchemistryco/Tangelo/issues/149. It checks the number of target qubits for some gates. It does not prevent multicontrolled-qubit gates nor custom gates.
=> Check for the number of target qubits

tangelo/toolboxes/ansatz_generator/tests/test_ansatz_util.py, tangelo/toolboxes/circuits/lcu.py, tangelo/toolboxes/circuits/tests/test_lcu.py
This implements the Linear Combination of Unitaries algorithm. 
Both the standard form for any operator and the truncated taylor series form are included.
=> lcu implementation

tangelo/algorithms/variational/vqe_solver.py
To fix another inconsistent behavior, we change the type of QubitHamiltonian to QubitOperator. This PR fixes an error that was raised because QubitOperator do not have mapping nor up_then_down as attributes.
=> Bug VQE.operator_expectation

tangelo/linq/circuit.py, tangelo/linq/tests/test_circuits.py
Allow users to traverse a circuit object, in order to iterate over gates.
```python
gates = ['H', 'X', 'CNOT', 'RZ']
c = Circuit(gates)
for g in c:
print(g)
```
=> Iterable circuit

tangelo/toolboxes/molecular_computation/tests/test_molecule.py
pyscf 2.1.0 changed the axis definition for c2v (https://github.com/pyscf/pyscf/issues/1201, https://github.com/pyscf/pyscf/pull/1393)
=> c2v axis definition change

.github/workflows/continuous_integration.yml, tangelo/linq/gate.py, tangelo/linq/tests/test_translator.py, tangelo/linq/translator/__init__.py, tangelo/linq/translator/translate_qiskit.py
Change `translate_qiskit` such that a qiskit.QuantumCircuit with supported gates can be translated to Circuit format.
=> translate qiskit.QuantumCircuit to Circuit 

tangelo/algorithms/variational/adapt_vqe_solver.py, tangelo/toolboxes/ansatz_generator/adapt_ansatz.py
Superfluous qubits (2) were initialized in ADAPTSolver with the scBK mapping. This fix issue #186.
=> Superfluous qubits with scBK in ADAPTSolver

tangelo/toolboxes/qubit_mappings/jkmn.py
Related to issue #211. Implementation of QCC is using the numpy broadcasting function, thus raising an error when selecting the JKMN mapping (the vector is a list).
=> JKMN vector prep should return an array of int

tangelo/toolboxes/molecular_computation/molecule.py
This attributes was meant to store the number of orbitals when using a minimal basis set. Changing the default basis cause this attribute to output wrong values, thus causing inconsistencies. This attribute is not used in our code base.
=> Remove the n_min_orbitals attribute

tangelo/toolboxes/qubit_mappings/jkmn.py, tangelo/toolboxes/qubit_mappings/tests/test_mapping_transform.py
The previous implementation resulted in a Qubit Hamiltonian that had real and imaginary parts. This change ensures that a real FermionOperator will be mapped to a real QubitOperator. (i.e. even number of Y elements with real coefficient or odd number of Y elements terms with imaginary coefficient)
=> Change JKMN Majorana definition so mapped Hamiltonian is real

tangelo/algorithms/variational/tests/test_iqcc_ilc_solver.py
I noticed there are 2 possible solutions (-1.638999 and -1.638197) with the iqcc_ilc_h4_cation test. This is maybe an underlying consequence of the iQCC-ILC algorithm.
=> Relaxing iqcc_ilc_h4_cation test

examples/overview_endtoend.ipynb, tangelo/toolboxes/post_processing/__init__.py, tangelo/toolboxes/post_processing/histogram.py, tangelo/toolboxes/post_processing/tests/test_histogram.py
Histogram class provides functions to manipulate results from an experiment. The two highlights are the `aggregate_histograms` (or `__add__` method) and `post_select` functions. The former one combines many histograms into a single one. The later function removes data according to the outcome of a (or many) qubit(s).
=> Histogram class

tangelo/linq/qpu_connection/ionq_connection.py
Aims to fix #216. Highlights:
- Added a verbose options to `IonQConnection`.
- Added `wait_time` argument (default 60s) to set the time between queries to IonQ API.
- If `verbose=True`, when the job status changes, it is printed.
Minimal script I used to test the thing:
```python
from tangelo.linq.qpu_connection import IonQConnection
from tangelo.linq import Gate, Circuit
qc = Circuit([Gate("X", 0), Gate("H", 0), Gate("CNOT", 1, 0)])
ionq = IonQConnection(verbose=True)
job_id = ionq.job_submit("simulator", qc, 10**3, "Test_verbose_true")
ionq.job_results(job_id, wait_time=1)
```
Output
```shell
Job submission  ID :: db48a7a5-28e8-4163-8cfe-daf4a5a5e2f6       status :: ready
Job info        ID:: db48a7a5-28e8-4163-8cfe-daf4a5a5e2f6        status :: submitted 
Job info        ID:: …
```
=> IonQConnection verbosity and wait time for job_results

tangelo/linq/gate.py, tangelo/linq/tests/test_gates.py
Some of our functions return a list of gates such as measurement_basis_gates. Without a repr method printing this return results in the output
```
>>> from tangelo.linq import Gate
>>> from tangelo.linq.helpers.circuits import measurement_basis_gates
>>> m = measurement_basis_gates(((0, "Y"), (1, "X")))
>>> print(m)
[{}, {}]
>>> m
[{}, {}]
```
With repr, the following output occurs.
```
>>> from tangelo.linq.helpers.circuits import measurement_basis_gates
>>> m = measurement_basis_gates(((0, "Y"), (1, "X")))
>>> print(m)
[Gate(name='RX', target=[0], parameter=1.5707963267948966), Gate(name='RY', target=[1], parameter=-1.5707963267948966)]
>>> m
[Gate(name='RX', target=[0], parameter=1.5707963267948966), Gate(name='RY', target=[1], parameter=-1.5707963267948966)]
```
Also …
=> add __repr__ method to Gate

tangelo/algorithms/variational/iqcc_solver.py, tangelo/algorithms/variational/tests/test_iqcc_solver.py, tangelo/algorithms/variational/vqe_solver.py, tangelo/toolboxes/ansatz_generator/qcc.py
Various bug fixes for iQCC.
- Trotter ordering not captured properly
- Used n_electrons instead of n_active_electrons.
=> trotter order and  active electrons for QCC/iQCC

tangelo/toolboxes/post_processing/__init__.py, tangelo/toolboxes/post_processing/histogram.py, tangelo/toolboxes/post_processing/post_selection.py, tangelo/toolboxes/post_processing/tests/test_post_selection.py
Adds the symmetry post-selection functionality
- Adds ancilla_symmetry_circuit function to append the symmetry verification circuit to a given circuit
- Adds post_select function to pst select on a dictionary of ancilla qubits
- Adds a convenience strip_post_selection function to remove the ancilla and aggregate the data as if no post-selection was used
- Adds tests for the functions
=> Symmetry post-selection

tangelo/toolboxes/ansatz_generator/ansatz_utils.py
The current implementation makes a simplification for when an identity qubit operator is trotterized that is not applicable for multiple controls. This is fixed.
=> Add multi-control support for trotterization

tangelo/algorithms/variational/tests/test_iqcc_ilc_solver.py, tangelo/algorithms/variational/tests/test_iqcc_solver.py, tangelo/toolboxes/ansatz_generator/_qubit_cc.py
JKMN mapping requires single flip index generators to converge using QCC. This PR allows a single flip index DIS group where the smallest size before was 2.
=> allow single flip index dis for qcc

tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/dmet/fragment.py, tangelo/toolboxes/ansatz_generator/qcc.py
DMET was throwing an error when using VQE-QCC. The fix is to trick the `isinstance` function in the QCC ansatz. Also, the `self.solver_fragment_dict` is not defined before simulate when calling `quantum_fragment_data`: the error raised was not helpful. With the fix, the `RuntimeError` with our custom message is printed.
=> DMET bug with QCC

tangelo/toolboxes/circuits/lcu.py
When multiplying qubit operators, zero coefficients can remain and this was not checked for in the LCU methods which caused nans.
For example
```python3
from tangelo.toolboxes.operators import QubitOperator
v1 = QubitOperator((), 1) + QubitOperator("X0", 0.5j)
v2 = QubitOperator((), 1) - QubitOperator("X0", 0.5j)
vdot = v1*v2
print([(term, coeff) for term, coeff in vdot.terms.items()])
```
outputs
```
[((), (1.25+0j)), (((0, 'X'),), 0j)]
```
=> check for small value lcu

tangelo/linq/qpu_connection/ibm_connection.py, tangelo/linq/tests/test_ibm_connection.py
Imports changed to reflect the changes made in the latest versions of qiskit / qiskit-runtime
=> Fix for IBMQConnection

tangelo/linq/circuit.py
Uses cirq's SVGCircuit such that the following code
```python3
from tangelo.linq import Circuit, Gate
circ = Circuit([Gate("CRZ", target=0, control=[1,2], parameter=1),
Gate("CNOT", target=0, control=1),
Gate("RZ", target=0, parameter=0.3)])
circ.draw()
```
makes
[output.svg.pdf](https://github.com/goodchemistryco/Tangelo/files/10427016/output.svg.pdf)
=> added draw method to circuit

tangelo/linq/target/target_cirq.py, tangelo/linq/target/target_qulacs.py, tangelo/linq/tests/test_translator_qubitop.py, tangelo/linq/translator/translate_cirq.py, tangelo/linq/translator/translate_pennylane.py, tangelo/linq/translator/translate_projectq.py, tangelo/linq/translator/translate_qiskit.py, tangelo/linq/translator/translate_qubitop.py, tangelo/linq/translator/translate_qulacs.py
Highlights:
- Added 2-way translation of qubit operator in several open-source packages (cirq, qulacs, pennylane, projectq). The translation in qulacs can now be handled by the proper function (issue https://github.com/qulacs/qulacs/issues/303 resolved);
- Added testsfor the translation from and to tangelo qubit operators;
- Used the `translate_operator` in the `target_cirq.py` and `target_qulacs.py` simulator files;
- Added docs to `QulacsSimulator.expectation_value_from_prepared_state` method.
- Moved the qubit operator cleaning into the main `translate_operator` function.
EDIT: @JamesB-1qbit asked me a question about the time execution for the qulacs translation. Apparently, the qulacs function was way slower (maybe due to the memory leak). Here are the times for 100 random 50-qubit …
=> Cirq, qulacs, pennylane and projectq operator translation functions

tangelo/linq/helpers/circuits/measurement_basis.py, tangelo/toolboxes/molecular_computation/rdms.py, tangelo/toolboxes/molecular_computation/tests/test_rdms.py
There were several bugs preventing users to use the compute rdms function:
1.
```python
{pauli_string_to_of(term): exp_val for term, exp_val in exp_data.items()}
``` 
to
```python
{pauli_string_to_of(term): exp_val for term, exp_val in exp_vals.items()}
``` 
(wrong dictionary).
2.
List are unhashable, changed output type of the `pauli_string_to_of` function to a tuple.
3. 
```python
if qterm in exp_vals:
exp_val = exp_vals[qterm] if qterm else 1.
```
was failing for the `()` term. I added a conditional statement.
4. Can now accept dictionaries with string ("IXYZ") or openfermion-like ((1, "X), (2, "Y"), ...) terms.
=> Fixed identity operator evaluation and extended the accepted input types in compute_rdms

tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/tests/dmet/test_osdmet.py
OS-DMET is giving good results for the test system that was available (LiO2). However, some tests with very simple systems resulted in energies with very significant errors (>1 Hartree). 
|                             System                            | DMET / Hartree | Mean-field / Hartree | CCSD / Hartree |
|:-------------------------------------------------------------:|:--------------:|:--------------------:|:--------------:|
| 7 H atoms, separation of 1.0 ang, minao, UHF                  | -2.8673        | -3.5606              | -3.6288        |
| 7 H atoms, separation of 1.0 ang, minao, ROHF                 | -2.5086        | -3.5527              | -3.6284        |
| 9 H atoms, separation of 1.0 ang, minao, UHF or ROHF          | No conv.       | -                    | - …
=> Disabling OS-DMET

tangelo/linq/target/backend.py, tangelo/linq/tests/test_simulator.py
I found an error in the `get_expectation_value` with a `desired_meas_result` and non-real `QubitOperator`
=> Bugfix: expectation of imaginary qubit_op with desired meas result

tangelo/linq/circuit.py
Just a look up dictionary really. No increase in memory, we apparently go faster than cirq itself to compute depth from scratch on circuits of depth 100K+ and 150K gates. Things are instant.
=> Depth function performance increase

tangelo/linq/__init__.py, tangelo/linq/circuit.py, tangelo/linq/target/backend.py, tangelo/linq/target/target_cirq.py, tangelo/linq/target/target_qiskit.py, tangelo/linq/target/target_qulacs.py, tangelo/linq/tests/test_circuits.py, tangelo/linq/tests/test_simulator.py
For a noiseless simulation with a desired_meas_result. This PR now implements
1. Circuit splitting between MEASURE operations to unitary_pieces
2. Simulate each unitary_piece and manually selected the desired_meas_result.
`sim.success_probability` is also saved.
=> deterministic desired_meas_result

tangelo/toolboxes/qubit_mappings/__init__.py, tangelo/toolboxes/qubit_mappings/combinatorial.py, tangelo/toolboxes/qubit_mappings/tests/test_combinatorial.py
Combinatorial mapping, as described in:
- Streltsov, A. I., Alon, O. E. & Cederbaum, L. S. General mapping for bosonic and fermionic operators in Fock space. Phys. Rev. A 81, 022124 (2010).
- Chamaki, D., Metcalf, M. & de Jong, W. A. Compact Molecular Simulation on Quantum Computers via Combinatorial Mapping and Variational State Preparation. Preprint at https://doi.org/10.48550/arXiv.2205.11742 (2022).
TODOs:
- ~~Remove the use of `h_to_qubitop` to be more efficient. There is maybe a way to add qubit operator terms on the fly during the construction of the `h_c` matrix (and thus removed the need to keep `h_c`).~~
- ~~Add tests.~~
Edit:
~~Tests are failing at the moment because of a bug in pennylane, see https://github.com/PennyLaneAI/pennylane/issues/3867.~~
=> Combinatorial mapping of fermionic Hamiltonians

tangelo/linq/gate.py, tangelo/linq/target/target_sympy.py, tangelo/linq/translator/translate_qubitop.py, tangelo/linq/translator/translate_sympy.py
Highlights:
- The best workflow I found to simplify the sympy expressions is to do a `simplify` then a `evalf` on the results.
- Add the `and n_qubits is None` condition to a check in `translate_qubitop`.
- Removed small probabilities from the bitstring dict.
EDIT: Removed `nsimplify` -> switched to `evalf()`.
=> Supporting symbols as parameters and add nsimplify to results

tangelo/problem_decomposition/dmet/_helpers/dmet_bath.py, tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py
Highlights:
- Make a `virtual_orbital_threshold` available. Before, it was hard-coded at `1e-13`. Changing this value gives us the ability of trading virtual orbital truncation and DMET energy accuracy. This is especially useful when working with small basis sets.
- Add a verbose print to output the occupancy eigenvalues (those are compared to the threshold).
- Force the occupancy eigenvalues to their absolute value (may be negative due to numerical noise, and this was introducing inconsistencies).
=> Set the DMET virtual orbital truncation threshold at the user level

tangelo/linq/tests/test_translator_circuit.py, tangelo/linq/translator/translate_cirq.py, tangelo/linq/translator/translate_qdk.py, tangelo/linq/translator/translate_qulacs.py
Previously CNOT ignored all controls except the first without warning. This changes the name in the circuit to CX.
=> Change multi-controlled CNOT to multi-controlled CX

tangelo/algorithms/classical/mp2_solver.py, tangelo/algorithms/classical/tests/test_mp2_solver.py, tangelo/toolboxes/ansatz_generator/uccsd.py
Support for initial MP2 parameters with a UHF mean-field.
Highlights:
- Support UMP2 initial parameters via `pyscf.mp.UMP2`.
- Moved the computation of MP2 parameters to the `MP2Solver` class (was in `UCCSD` before).
- Fixed a circular import when doing `from tangelo.toolboxes.ansatz_generator._unitary_cc_openshell import uccsd_openshell_get_packed_amplitudes` by moving the `MP2Solver` import after the initialiazation of the `UCCSD` ansatz.
=> Support for UMP2 initial parameters

tangelo/toolboxes/molecular_computation/integral_solver_pyscf.py
Support for defining a chkfile during the mean-field calculation. When providing a chkfile name to the `IntegralSolverPySCF` class (`IntegralSolverPySCF("your_chkfile_name.chk")`), it will consider using a file on disk to store mo coefficients / density matrix and other import quantities.
=> Checkfile for IntegralSolverPySCF

tangelo/linq/tests/test_translator_perf.py
This test takes a long time and does not print out the times anyway during continuous integration.
Running from terminal `python test_translator_perf.py` still runs the tests.
=> skip performance tests when using pytest

tangelo/problem_decomposition/dmet/_helpers/dmet_orbitals.py, tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/tests/dmet/test_dmet.py
Should fix #306 
Previously the Effective Core Potential term was not added to the fragment Fock matrix for RHF systems in DMETProblemDecomposition. This PR addresses that issue and adds a test to show that it is correctly returning the expected answer as described in #306.
=> DMET Effective Core Potential fix(related to #306)

.github/workflows/continuous_integration.yml, .github/workflows/run_psi4_test.yml, README.rst, setup.py
=> Change installation

tangelo/problem_decomposition/tests/dmet/test_dmet.py
Previous ECP check failed because DMET with 1 fragment has a result that is independent of the chemical potential. So `x0 != x1` sometimes returned `f(x0) == f(x1)`. This switches the optimizer for the test to minimize (f(x)**2).
=> DMET ecp test: change optimizer to minimize square

tangelo/toolboxes/ansatz_generator/uccsd.py
Right now. If someone uses psi4 to call VQESolver with default parameters, a generic error message is received when building.
```python3
from tangelo.algorithms.variational import VQESolver
from tangelo.molecule_library import mol_H4_sto3g
vqe = VQESolver({"molecule": mol_H4_sto3g})
vqe.build()
```
results in
```
ValueError: "PySCF is required for MP2 initial parameters in UCCSD"
```
Added information about other var_param options. Now results in:
```
ValueError: PySCF is required for MP2 initial parameters in UCCSD.
Other supported keywords for initializing variational parameters are {'random', 'ones'}. An array of length 14 can also be provided.
The above options can also be provided to variational algorithms through the 'initial_var_params' keyword.
```
=> improved Error message for MP2 initialization

tangelo/linq/target/target_qiskit.py, tangelo/linq/tests/test_translator_qubitop.py, tangelo/linq/translator/translate_qiskit.py
One bug from deepcopy not working anymore with `qiskit.result.marginal_counts` changed to inplace=True. 
We never resample result anyway.
`opflow` is deprecated. `PauliSumOp`->`SparsePauliOp`. See https://qiskit.org/documentation/migration_guides/opflow_migration.html
=> Qiskit interface: Bug workaround and PauliSumOp->SparsePauliOp

tangelo/toolboxes/qubit_mappings/combinatorial.py
Fix for the combinatorial mapping when `spin!=0`, i.e. when there are a different number of alpha and beta electrons. For convenience (if we want to work with a matrix), it ensures that the combinatorial integers are between 0 and 2^n_qubit - 1. As of now, when `spin!=0`, `n_choose_alpha != n_choose_beta` and the chosen integers suffer discontinuities. 
This has no effect on the number of qubit and the resulting qubit operators (as they are equivalent by remapping qubit indices). It also has no effect when `n_choose_alpha == n_choose_beta`.
=> Fix combinatorial mapping when spin!=0

.github/workflows/continuous_integration.yml, .github/workflows/run_psi4_test.yml
Currently adding (3.9, 3.10, 3.11) to see what happens. We are only running tests on 3.8 so far.
=> Adding more python versions to tests

tangelo/linq/target/backend.py, tangelo/linq/tests/test_simulator.py
n_shots was ignored in get_expectation_value if not paired with mixed state.
=> Bug Fix: n_shots parameter was ignored in get_expectation_value

tangelo/linq/gate.py, tangelo/linq/tests/test_gates.py
1. Checks that name is a string and raises a TypeError otherwise
2. Converts the string to uppercase to match our convention.
=> Convert name of Gate to uppercase when initializing

tangelo/toolboxes/circuits/lcu.py, tangelo/toolboxes/circuits/tests/test_lcu.py
A simple function that pre-computes the qubits used when calling the `get_truncated_taylor_series` function.
=> Function that returns the qubits used for Truncated Taylor Series

tangelo/algorithms/variational/tests/test_vqe_solver.py, tangelo/algorithms/variational/vqe_solver.py
Highlights:
- HiddenPrints is now set with the `VQESolver.verbose` option.
- Saving the energies via the `save_energies` option. Every `energy_estimation` call can now save the energy (to plot after the simulation).
=> Support for following VQE minimization in VQESolver

tangelo/algorithms/classical/ccsd_solver.py, tangelo/algorithms/classical/tests/test_ccsd_solver.py, tangelo/algorithms/classical/tests/test_fci_solver.py, tangelo/toolboxes/molecular_computation/integral_solver_psi4.py, tangelo/toolboxes/molecular_computation/integral_solver_pyscf.py, tangelo/toolboxes/molecular_computation/molecule.py
Classical solvers used the molecular coefficients from the initial Hartree-Fock calculation and not the molecular coefficients stored in the SecondQuantizedMolecule object. This fixes it for PySCF and Psi4.
=> Classical solver uses mo_coeff from SecondQuantizedMolecule

tangelo/algorithms/variational/iqcc_ilc_solver.py, tangelo/toolboxes/ansatz_generator/_qubit_ilc.py, tangelo/toolboxes/ansatz_generator/ilc.py, tangelo/toolboxes/ansatz_generator/tests/test_ilc.py
There were a few sign errors/ operator order errors that caused the ILC parameters generated from the `get_ilc_params_by_diag` to not match the energy when placed in circuit form.
=> Small fixes for ILC

tangelo/linq/qpu_connection/ibm_connection.py
Add the option to specify the instance ("my_hub/my_group/my_project" format) in the IBM connection class.
=> Set the instance in a Qiskit runtime job

tangelo/linq/circuit.py, tangelo/linq/qpu_connection/ibm_connection.py, tangelo/linq/tests/test_circuits.py, tangelo/toolboxes/operators/tests/test_trim_trivial_qubits.py, tangelo/toolboxes/operators/trim_trivial_qubits.py
Added the option to split circuit without reindexing the qubits. 
Used for a small bug fix in `trim_trivial_qubits` where two unentangled circuits that were not trivial were not added properly.
=> Added trim_qubits option to Circuit.split()

tangelo/helpers/utils.py, tangelo/linq/__init__.py, tangelo/linq/circuit.py, tangelo/linq/target/backend.py, tangelo/linq/target/target_cirq.py, tangelo/linq/target/target_qdk.py, tangelo/linq/target/target_qiskit.py, tangelo/linq/target/target_qulacs.py, tangelo/linq/target/target_stim.py, tangelo/linq/target/target_sympy.py, tangelo/linq/tests/test_circuits.py, tangelo/linq/tests/test_simulator.py, tangelo/linq/translator/translate_cirq.py, tangelo/linq/translator/translate_qulacs.py, tangelo/toolboxes/post_processing/post_selection.py
The initial version of measurement controlled operations.
Users introduce a "CMEASURE" Gate
Three choices
1) Dictionary for parameter, i.e. `Gate("CMEASURE", target, parameter= {"0": List[Gate], "1": List[Gate]})`
2) Function in the parameter, i.e. `Gate("CMEASURE", target, parameter=function(measurement))`
3) Subclass of ClassicalControl instantiated when initializing the Circuit, i.e. circuit = Circuit(List[Gate], cmeasure_control=Class)
The last is by far the most flexible as can be seen for iterative phase estimation in `test_simulator.py`.
=> Measurement Controlled operations

tangelo/linq/target/target_qiskit.py
A test was failing because
```python3
backend = qiskit_aer.AerSimulator(method="statevector", noise_model=qiskit_noise_model)
translated_circuit = self.qiskit.transpile(translated_circuit, backend)
translated_circuit.save_statevector()
sim_results = backend.run(translated_circuit, shots=1).result()
```
works but our current version does not
```python3
backend = qiskit_aer.AerSimulator(method="statevector")
translated_circuit = self.qiskit.transpile(translated_circuit, backend)
translated_circuit.save_statevector()
sim_results = backend.run(translated_circuit, shots=1, noise_model=qiskit_noise_model).result()
```
=> switched where qiskit_noise_model is specified

tangelo/problem_decomposition/dmet/fragment.py
A bug was causing this code to crash
```python
from tangelo import SecondQuantizedMolecule
from tangelo.problem_decomposition.dmet.dmet_problem_decomposition import Localization, DMETProblemDecomposition
xyz_H4 = [("H", [0.0, 0.0, i*2.5]) for i in range(4)]
mol = SecondQuantizedMolecule(xyz_H4, q=0, spin=0, basis="sto-3g")
my_backend_options = {"target": "qulacs", "n_shots": None, "noise_model": None}
solvers_options = {"backend_options": my_backend_options}
opt_dmet = {"molecule": mol,
"fragment_atoms": [1]*4,
"fragment_solvers": ["vqe"]*4,
"solvers_options": [solvers_options]*4,
"electron_localization": Localization.meta_lowdin,
"verbose": True
}
dmet = DMETProblemDecomposition(opt_dmet)
dmet.build()
energy = dmet.simulate()
print(energy)
```
The root cause of this was because the …
=> Bugfix: DMET fragment object initialization from IntegralSolver fixed

tangelo/toolboxes/molecular_computation/fno.py, tangelo/toolboxes/molecular_computation/tests/test_fno.py
Our MP2 backend (PySCF) convert automatically the RMP2 to UMP2 when an ROHF mean field is used. This has the side effect of setting the FNO MO coeffs differently per spin, therefore enforcing us to use UHF for spin!=0 molecules.
=> NotImplementedError for ROHF in FNO

.github/workflows/continuous_integration.yml, tangelo/helpers/utils.py, tangelo/linq/noisy_simulation/noise_models.py, tangelo/linq/target/target_qiskit.py, tangelo/linq/tests/test_translator_circuit.py, tangelo/linq/translator/translate_openqasm.py
Highlights:
- Fix changes related to Qiskit 1.0.
- Left `qsharp` out of the tests. Work still to be done to support the QDK.
For [qsharp](https://learn.microsoft.com/en-us/azure/quantum/how-to-migrate-to-modern):
"Most of the in-memory simulators from the Classic QDK have been deprecated, leaving the [sparse simulator](https://learn.microsoft.com/en-us/azure/quantum/sparse-simulator) as the default local simulator in VS Code and the Azure Quantum portal."
- There is an error in PySCF >=2.5.0 when computing MP2 initial parameters for UCCSD. This error isn't showing when using PySCF <= 2.4.0.
=> Fix: Qiskit v1.0.0

tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/tests/dmet/test_dmet_vqe.py
Added an option to define a function to define the DMET fragment active space. As the orbital overlap could change with the chemical potential, it is not trivial to define the `frozen_orbitals` manually.
Here is an example of how to leverage this option. In this example, we define the fragment active space as HOMO to LUMO, so every fragment in JW (for restricted mean-field DMET) would be 4 qubits.
```python
from tangelo import SecondQuantizedMolecule
from tangelo.problem_decomposition import DMETProblemDecomposition
xyz_H10 = [
("H", ( 0.970820393250,  0.000000000000, 0.)),
("H", ( 0.785410196625,  0.570633909777, 0.)),
("H", ( 0.300000000000,  0.923305061153, 0.)),
("H", (-0.300000000000,  0.923305061153, 0.)),
("H", (-0.785410196625,  0.570633909777, 0.)),
("H", (-0.970820393250, …
```
=> Added an option for a callable when defining fragment active space

tangelo/linq/qpu_connection/ibm_connection.py, tangelo/linq/tests/test_ibm_connection.py, tangelo/linq/translator/translate_qiskit.py
Update of code. Translation function for qiskit now supports additional argument for users to specify whether a classical register should be added to the circuit or not.
=> Fix for qiskit ibm runtime v 0.22

tangelo/problem_decomposition/dmet/dmet_problem_decomposition.py, tangelo/problem_decomposition/tests/dmet/test_dmet.py, tangelo/problem_decomposition/tests/dmet/test_osdmet.py
This is a low-hanging fruit implementation of HF and MP2 solvers with DMET.
Note: This is untested for the unrestricted MP2, and won't work with UHF.
=> DMET with HF and MP2 solvers

.github/workflows/continuous_integration.yml, .github/workflows/run_psi4_test.yml
The Pennylane dependency is not supporting 3.8 anymore.
Qulacs is currently having installation trouble for 3.12, which they should be working on (https://github.com/qulacs/qulacs/issues/645)
=> Removing Python 3.8 support, and adding 3.12

.github/workflows/deploy_docs.yml, .gitignore
Resolve #385 
The automatically deployed documentation is available at: https://king-p3nguin.github.io/Tangelo/
Settings for GitHub Pages is as follows:
(I am contributing to this project as a unitaryHACK participant)
=> Add automatic documentation deployment workflow

.github/workflows/continuous_integration.yml, tangelo/toolboxes/circuits/qre.py, tangelo/toolboxes/circuits/tests/test_qre.py, tangelo/toolboxes/molecular_computation/molecule.py
Interface to other software quantum resource estimation (QRE) tools. 
As of now, it supports:
- [Benchq](https://github.com/zapatacomputing/benchq)
- [Pennylane](https://github.com/PennyLaneAI/pennylane)
- [PyLIQTR](https://github.com/isi-usc-edu/pyLIQTR.git)
There is no test at the moment for PyLIQTR because it is only working with a specific `cirq` version (`cirq-core==1.3.0.dev20231018023458`), and it is breaking the `tangelo.linq` module.
=> Interface to quantum resource estimation (QRE) tools
